spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:neupinion;MODE=MySQL

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

cors:
  mapping: "/**"
  origins: "*"
  headers: "*"
  methods: "*"

jwt:
  secret-code: alksejgihslkdjf2r2i40djsbfkajdslfkjkljalskd
  access-token-valid-time: 12000 # 12초
  refresh-token-valid-time: 6000000 # 10분

oauth2:
  google:
    access-token-url: http://localhost:8000/token
    member-info-url: http://localhost:8000/userinfo
    client-id: 12345678901234567890123456789012
    client-secret: 12345678901234567890123456789012
    redirect-uri: http://localhost:8080/redirect

cookie:
  valid-time: 12000 # 12초
