spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:neupinion;MODE=MySQL

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

cors:
  mapping: "/**"
  origins: "*"
  headers: "*"
  methods: "*"
